when:
  event: tag
  branch: main

steps:
  build-production:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: 10.10.10.112:5000
      repo: coinluxer/clx-etl
      tags:
        - ${CI_COMMIT_TAG}
      skip_tls_verify: true
      cache: true

  deploy-production:
    depends_on:
      - build-production
    image: alpine
    environment:
      HOST: 10.10.10.132
      REGISTRY: 10.10.10.112:5000
      IMAGE_NAME: coinluxer/clx-etl

      CONTAINER_NAME: clx-etl

      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
      SSH_KNOWN_HOSTS:
        from_secret: SSH_KNOWN_HOSTS
      DORIS_PASSWORD:
        from_secret: DORIS_PASSWORD_PROD
      MYSQL_PASSWORD:
        from_secret: MYSQL_PASSWORD_PROD

    commands:
      - apk add openssh-client docker-cli
      - mkdir -p ~/.ssh
      - printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - printf "%s" "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

      - |
          ssh -o StrictHostKeyChecking=yes hhe@$HOST "
            set -xe;
            mkdir -p /opt/coinluxer/clx-etl/logs;

            docker pull $REGISTRY/$IMAGE_NAME:${CI_COMMIT_TAG};

            docker stop $CONTAINER_NAME || true;
            docker rm $CONTAINER_NAME || true;

            docker run -d \
              --name $CONTAINER_NAME \
              --restart always \
              --log-driver json-file \
              --log-opt max-size=50m \
              --log-opt max-file=2 \
              -e ENV=production \
              -e VERSION=${CI_COMMIT_TAG} \
              -e DORIS_HOST=192.168.50.131 \
              -e DORIS_HTTP_PORT=8030 \
              -e DORIS_PORT=9030 \
              -e DORIS_USER=etl \
              -e DORIS_PASSWORD=$DORIS_PASSWORD \
              -e DORIS_DB=coinluxer \
              -e MYSQL_HOST=192.168.50.132 \
              -e MYSQL_PORT=3306 \
              -e MYSQL_USER=etl \
              -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
              -e MYSQL_DB=coinluxer \
              -v /opt/coinluxer/clx-etl/logs:/app/logs \
              $REGISTRY/$IMAGE_NAME:${CI_COMMIT_TAG};

            echo 'Waiting 15 seconds...';
            sleep 15;

            STATUS=\$(docker inspect -f '{{.State.Status}}' $CONTAINER_NAME)
            RESTARTS=\$(docker inspect -f '{{.RestartCount}}' $CONTAINER_NAME)

            if [ \"\$STATUS\" != \"running\" ]; then
              echo '❌ PROD container is NOT running:' \$STATUS
              docker logs $CONTAINER_NAME
              exit 1
            fi

            if [ \$RESTARTS -gt 0 ]; then
              echo '❌ PROD container restarted' \$RESTARTS 'times.'
              docker logs $CONTAINER_NAME
              exit 1
            fi

            echo 'PROD OK 🚀';
          "

  notify-success:
    when:
      status: success
    depends_on:
      - deploy-production
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "✅ `[ clx-etl : ${CI_COMMIT_TAG} ]` PROD Deploy Success"

  notify-failure:
    when:
      status: failure
    depends_on:
      - deploy-production
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "❌ `[ clx-etl : ${CI_COMMIT_TAG} ]` PROD Deploy Failed"
